version: '3.8'

services:
  front:
    build:
      context: ./front
    ports:
      - "3000:80"
    networks:
      - app-network

  back:
    build:
      context: ./back
    ports:
      - "3001:3000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=mysql://user:password@mysql:3306/database
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
